---
- name: Set up Kubernetes prerequisites
  hosts: zsh_setup
  become: yes

  tasks:
    - name: Load overlay kernel module
      command: modprobe overlay

    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter

    - name: Add sysctl settings for Kubernetes
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add Docker's repository
      deb822_repository:
        repo: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Architectures: [{{ ansible_architecture }}]
          Signed-By: /etc/apt/keyrings/docker.asc
        state: present
        filename: docker

    - name: Add Kubernetes' GPG key
      get_url:
        url: https://pkgs.k8s.io/{{ k8s_release }}/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

    - name: Add Kubernetes' repository
      deb822_repository:
        repo: |
          Types: deb
          URIs: https://pkgs.k8s.io/{{ k8s_release }}/deb/
          Suites: /
          Signed-By: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        state: present
        filename: kubernetes

    - name: Install containerd.io
      apt:
        update_cache: yes
        name: containerd.io
        state: present

    - name: Generate default containerd config
      command:
        cmd: containerd config default
      register: containerd_default_config

    - name: Write default containerd config to file
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_default_config.stdout }}"

    - name: Set SystemdCgroup to true in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        daemon_reload: yes

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: 
          - "kubeadm={{ k8s_version }}-*"
          - "kubelet={{ k8s_version }}-*"
          - "kubectl={{ k8s_version }}-*"
        state: present

    - name: Hold kubeadm, kubelet, and kubectl packages
      shell: |
        apt-mark hold kubelet kubeadm kubectl

    - name: Add control plane to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ cluster_host_ipv4_address }} k8scp"
        state: present

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes